
/* Countries */
INSERT INTO country (country_code, name)
VALUES
    ('HR', 'Croatia'),
    ('US', 'United States'),
    ('CA', 'Canada'),
    ('MX', 'Mexico'),
    ('BR', 'Brazil'),
    ('AR', 'Argentina'),
    ('AU', 'Australia'),
    ('NZ', 'New Zealand'),
    ('ZA', 'South Africa'),
    ('EG', 'Egypt'),
    ('TH', 'Thailand'),
    ('ID', 'Indonesia'),
    ('MY', 'Malaysia'),
    ('PH', 'Philippines'),
    ('GR', 'Greece'),
    ('IT', 'Italy'),
    ('ES', 'Spain'),
    ('FR', 'France'),
    ('PT', 'Portugal'),
    ('TR', 'Turkey'),
    ('AE', 'United Arab Emirates'),
    ('OM', 'Oman'),
    ('IN', 'India'),
    ('VN', 'Vietnam'),
    ('JM', 'Jamaica'),
    ('BB', 'Barbados'),
    ('CY', 'Cyprus'),
    ('BA', 'Bosnia and Herzegovina'),
    ('CR', 'Costa Rica'),
    ('DO', 'Dominican Republic'),
    ('FI', 'Finland'),
    ('SE', 'Sweden'),
    ('NO', 'Norway'),
    ('DK', 'Denmark'),
    ('BS', 'Bahamas'),
    ('MU', 'Mauritius'),
    ('MV', 'Maldives'),
    ('MT', 'Malta'),
    ('BN', 'Brunei'),
    ('LC', 'Saint Lucia'),
    ('GD', 'Grenada'),
    ('TO', 'Tonga'),
    ('FJ', 'Fiji'),
    ('VC', 'Saint Vincent and the Grenadines'),
    ('BZ', 'Belize'),
    ('TT', 'Trinidad and Tobago'),
    ('SR', 'Suriname'),
    ('GY', 'Guyana'),
    ('KY', 'Cayman Islands'),
    ('TC', 'Turks and Caicos Islands')
;

/* Regions */
INSERT INTO region (country_id, name)
VALUES
    (102, 'Bjelovar-Bilogora'),
    (102, 'Brod-Posavina'),
    (102, 'Dubrovnik-Neretva'),
    (102, 'Zagreb City'),
    (102, 'Istria'),
    (102, 'Karlovac'),
    (102, 'Koprivnica-Križevci'),
    (102, 'Krapina-Zagorje'),
    (102, 'Lika-Senj'),
    (102, 'Medimurje'),
    (102, 'Osijek-Baranja'),
    (102, 'Pozega-Slavonia'),
    (102, 'Kvarner'),
    (102, 'Sisak-Moslovina'),
    (102, 'Split-Dalmatia'),
    (102, 'Sibenik-Knin'),
    (102, 'Varazdin'),
    (102, 'Virovitica-Podravina'),
    (102, 'Vukovar-Srijem'),
    (102, 'Zadar'),
    (102, 'Zagreb County')
;
