spring:
  datasource:
    url: jdbc:postgresql://ep-billowing-sound-02425339.eu-central-1.aws.neon.tech/odmaralica
    username: msakac
    password: DMgAFOEUVH18

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: org.foi.diplomski.msakac.odmaralica

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR
    org.foi.diplomski.msakac.odmaralica: DEBUG

jwt:
  secretKey: secret
  issuer: http://localhost
  expirationMinute: 10

swagger:
  app-name: Odmaralica
  app-description: "Odmaralica Backend - Tehnologije: Spring Boot(2.7.4), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger"
  app-version: 1.0.0

